package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"synthos-collective/internal/wallet"
)

type identityFile struct {
	NodeID      string `json:"node_id"`
	Address     string `json:"address"`
	PublicKey   string `json:"public_key"`
	PrivateKey  string `json:"private_key"`
	Fingerprint string `json:"fingerprint"`
}

type validatorConfig struct {
	NodeID   string            `json:"node_id"`
	PeerKeys map[string]string `json:"peer_keys"`
}

type nodeConfig struct {
	NodeID      string            `json:"node_id"`
	DataDir     string            `json:"data_dir"`
	IsValidator bool              `json:"is_validator"`
	RPCListen   string            `json:"rpc_listen"`
	GenesisPath string            `json:"genesis_path"`
	Peers       []string          `json:"peers"`
	HTTPPeers   []string          `json:"http_peers"`
	ListenAddr  string            `json:"listen_addr"`
	PrivateKey  string            `json:"private_key"`
	Validators  []string          `json:"validators"`
	PeerKeys    map[string]string `json:"peer_keys"`
}

func main() {
	var outDir string
	var networkDir string
	var rpcListen string
	var listenAddr string
	var peerBaseRPCPort int
	flag.StringVar(&outDir, "out", ".synthos/push-button-node", "output directory for local push-button node material")
	flag.StringVar(&networkDir, "network-dir", ".synthos/open-network-11-15", "validator network directory generated by cmd/opennet")
	flag.StringVar(&rpcListen, "rpc-listen", ":8120", "local RPC listen address for the push-button node")
	flag.StringVar(&listenAddr, "listen-addr", ":9020", "local TCP listen address for the push-button node")
	flag.IntVar(&peerBaseRPCPort, "peer-base-rpc-port", 8111, "first local validator RPC port")
	flag.Parse()

	if err := os.MkdirAll(outDir, 0o700); err != nil {
		panic(err)
	}

	networkDir = cleanPath(networkDir)
	outDir = cleanPath(outDir)
	genesisPath := filepath.Join(networkDir, "genesis.json")
	mustExist(genesisPath)

	identity := loadOrCreateIdentity(filepath.Join(outDir, "identity.private.json"))
	validators, peerKeys := loadValidatorRegistry(networkDir)
	httpPeers := make([]string, 0, len(validators))
	for i := range validators {
		httpPeers = append(httpPeers, fmt.Sprintf("http://127.0.0.1:%d", peerBaseRPCPort+i))
	}

	cfg := nodeConfig{
		NodeID:      identity.NodeID,
		DataDir:     filepath.Join(outDir, "data"),
		IsValidator: false,
		RPCListen:   rpcListen,
		GenesisPath: genesisPath,
		Peers:       []string{},
		HTTPPeers:   httpPeers,
		ListenAddr:  listenAddr,
		PrivateKey:  identity.PrivateKey,
		Validators:  validators,
		PeerKeys:    peerKeys,
	}

	configDir := filepath.Join(outDir, "config")
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		panic(err)
	}
	writeJSON(filepath.Join(outDir, "node.json"), cfg, 0o600)
	writeJSON(filepath.Join(configDir, "node.json"), cfg, 0o600)
	writeJSON(filepath.Join(outDir, "identity.public.json"), map[string]any{
		"node_id":     identity.NodeID,
		"address":     identity.Address,
		"public_key":  identity.PublicKey,
		"fingerprint": identity.Fingerprint,
		"rpc_url":     "http://127.0.0.1" + rpcListen,
		"http_peers":  httpPeers,
		"capabilities": []string{
			"immune_node",
			"economist",
			"governor",
			"communicator",
			"simulator",
			"enforcer",
			"citizen",
		},
	}, 0o644)

	fmt.Printf("Push-button SYNTHOS node initialized in %s\n", outDir)
	fmt.Printf("Node ID: %s\n", identity.NodeID)
	fmt.Printf("Address: %s\n", identity.Address)
	fmt.Printf("Public key: %s\n", identity.PublicKey)
	fmt.Printf("Local RPC: http://127.0.0.1%s\n", rpcListen)
}

func loadOrCreateIdentity(path string) identityFile {
	if b, err := os.ReadFile(path); err == nil {
		var identity identityFile
		if err := json.Unmarshal(b, &identity); err != nil {
			panic(err)
		}
		if identity.PrivateKey == "" || identity.PublicKey == "" || identity.NodeID == "" {
			panic("existing identity file is missing required fields")
		}
		return identity
	}

	w, err := wallet.New()
	if err != nil {
		panic(err)
	}
	addr, err := w.Address()
	if err != nil {
		panic(err)
	}
	pub, err := w.PublicKeyHex()
	if err != nil {
		panic(err)
	}
	priv, err := w.PrivateKeyHex()
	if err != nil {
		panic(err)
	}
	fingerprint, err := w.Fingerprint()
	if err != nil {
		panic(err)
	}
	identity := identityFile{
		NodeID:      "push-button-node-" + strings.TrimPrefix(fingerprint, "0x"),
		Address:     string(addr),
		PublicKey:   pub,
		PrivateKey:  priv,
		Fingerprint: fingerprint,
	}
	writeJSON(path, identity, 0o600)
	return identity
}

func loadValidatorRegistry(networkDir string) ([]string, map[string]string) {
	var validators []string
	peerKeys := map[string]string{}
	for i := 11; i <= 15; i++ {
		path := filepath.Join(networkDir, fmt.Sprintf("validator-%d.json", i))
		mustExist(path)
		var cfg validatorConfig
		b, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		if err := json.Unmarshal(b, &cfg); err != nil {
			panic(err)
		}
		if cfg.NodeID == "" {
			cfg.NodeID = fmt.Sprintf("validator-%d", i)
		}
		validators = append(validators, cfg.NodeID)
		for id, pub := range cfg.PeerKeys {
			peerKeys[id] = pub
		}
	}
	return validators, peerKeys
}

func cleanPath(path string) string {
	abs, err := filepath.Abs(path)
	if err != nil {
		panic(err)
	}
	return abs
}

func mustExist(path string) {
	if _, err := os.Stat(path); err != nil {
		panic(fmt.Errorf("%s does not exist", path))
	}
}

func writeJSON(path string, value any, perm os.FileMode) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(path, data, perm); err != nil {
		panic(err)
	}
}
