name = "synthos-validator"
main = "src/index.js"
account_id = "f2e9e2935f6f8231889b7535a9cd4b18"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment 1
[env.validator1]
name = "synthos-validator-1"
vars = { VALIDATOR_ID = "validator-1", PRIVATE_KEY = "55e146902e0e7ab12e9c39c81c17bbe7b26c4cb8ebe1fd8d70e1354f28322118c86406828d8da355e9ea833d78aefb502e84d2cfd0652886e660a2f4418d89c3", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator1.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 2
[env.validator2]
name = "synthos-validator-2"
vars = { VALIDATOR_ID = "validator-2", PRIVATE_KEY = "f999d1bd19f40ac5198927fcf52101167f36062b46b26f510f78688ceb15667f4007f305b3fcf4ff44e494f04370460fdc9ba41d60459cf03ad469c8891a4862", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator2.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 3
[env.validator3]
name = "synthos-validator-3"
vars = { VALIDATOR_ID = "validator-3", PRIVATE_KEY = "1e934a2fb2ff29ccd347d797a0afcb0a080c1ae64f7032ccdc048a61a1a895ce06f14ac46f57e5aead99400d44be00cab4c0978300b333c2a44d629d629ac3e9", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator3.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 4
[env.validator4]
name = "synthos-validator-4"
vars = { VALIDATOR_ID = "validator-4", PRIVATE_KEY = "432913cdca996df1ecc59d28c59e055106d9e5e51bc05ce51e840b6ab36f555b8e4a9098ffca6ca72ad358a21d078f2a2c8636f1b6684bb59bb7acfa597c2c0d", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator4.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 5
[env.validator5]
name = "synthos-validator-5"
vars = { VALIDATOR_ID = "validator-5", PRIVATE_KEY = "5efcf91ce48b71efdc9174f9a9cf200f6e7b476694500d75e4767d9b957b0f97bb84b0684968e17ea1ca9d6c818d12c4814f65b0bbe1e4c874ea56cd552ee851", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator5.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 6
[env.validator6]
name = "synthos-validator-6"
vars = { VALIDATOR_ID = "validator-6", PRIVATE_KEY = "133911e3e9ec20093777347b24469fce3f93e37d2b9c880f1eeabab7b9d2e597470362ee4237c04daf5467bbf6d33e531110cd7f3e8cb7800146d8e1f26b71c5", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator6.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 7
[env.validator7]
name = "synthos-validator-7"
vars = { VALIDATOR_ID = "validator-7", PRIVATE_KEY = "0ced130a464bc8a1abad13e3c9f46d24b45643304b1caf78bbb22ad715221ea0554d4d543cef4955ac9fd0a77b204dcb7e7c525cd213e79ad6e978de98167360", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator7.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 8
[env.validator8]
name = "synthos-validator-8"
vars = { VALIDATOR_ID = "validator-8", PRIVATE_KEY = "5d07527b8c0e4126a969d43bc2313a11d3cb59ecd1a8ab3c95e319b83db46e5a5e1c7f77b92e84dc92624a7f1081241959828ef4697903a41ee2bfc36af59076", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator8.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 9
[env.validator9]
name = "synthos-validator-9"
vars = { VALIDATOR_ID = "validator-9", PRIVATE_KEY = "f715504e38d01380ae6926e2f10843d319b06f5a9ff09e59a25f2a6de2ba2fee401d7e1498b7a965e09ff2267ba447f45cc0789122c9c231041f9278ea8d657c", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator9.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 10
[env.validator10]
name = "synthos-validator-10"
vars = { VALIDATOR_ID = "validator-10", PRIVATE_KEY = "2382351da715feba9d8d569fcc3ff8f8e75c4aa4296a9b62810e51e47229069b280d5dc8d94244f29ca9bda9f65512ac742e8affca182f7d0441d28171d6a09e", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator10.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 11
[env.validator11]
name = "synthos-validator-11"
vars = { VALIDATOR_ID = "validator-11", PRIVATE_KEY = "390a0138c3c795da357d5387ff86c9aa20c12e58fdc044f3ebf109b329430a1fa4fe13f7b863e688168ab4075a266b7871fdd370966584e50e78d84254e00f75", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator11.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 12
[env.validator12]
name = "synthos-validator-12"
vars = { VALIDATOR_ID = "validator-12", PRIVATE_KEY = "c319be4d633abf555560f784c4594924d76d7d86aad0ebbb3aeb9ea94413d6d6f4fe4e441f6542332c1e14932f89deedcb0940c8bf82ec739c586cf3769d2f7e", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator12.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 13
[env.validator13]
name = "synthos-validator-13"
vars = { VALIDATOR_ID = "validator-13", PRIVATE_KEY = "c7139e675baf3ef9530125eb3ee0fa6a0629a9ac639706889d3415b88a293f694fbb824f7bb9838c0338d3808fe9b5c08fb92e7e288d2736f77820d7d8795241", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator13.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 14
[env.validator14]
name = "synthos-validator-14"
vars = { VALIDATOR_ID = "validator-14", PRIVATE_KEY = "b01147932bcc8e14db576420ceba36672bfa668ecc9e8193714f01f0e8dfaecd8e9d7bfe4cafcfbc7da5f40f06a1bd6ec56fec46078241e58c02071532e03dcb", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator14.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"

# Environment 15
[env.validator15]
name = "synthos-validator-15"
vars = { VALIDATOR_ID = "validator-15", PRIVATE_KEY = "811bd88ed50e3b121aec27edbe7acea17554a701983d797a5ade540db5829ebc35c57c962d65b79c11999220be521c93a27f8382012e4b796dab118fbb86a874", NETWORK = "mainnet" }
triggers = { crons = ["*/5 * * * *"] }
[[env.validator15.r2_buckets]]
binding = "VALIDATOR_BUCKET"
bucket_name = "synthos-validators"
