// researchAgent.js – real research AI agent using OpenAI
// Expects JSON body: { query: string }
// Returns a concise research summary generated by the LLM.

import { openai } from "../openaiClient.js"; // reuse existing client configuration

export async function generateResearch(query) {
  const prompt = `You are a research assistant. Provide a concise, factual summary (max 200 words) for the following query, citing any relevant sources or facts when possible. Do not add fluff.

Query: "${query}"`;
  const response = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: [{ role: "system", content: "You are a helpful research assistant." }, { role: "user", content: prompt }],
    temperature: 0.2,
    max_tokens: 500,
  });
  const summary = response.choices[0].message.content.trim();
  return { summary };
}
